### ISSUE TITLE
While running "phyloFlash_makedb.pl --remote" FATAL ERROR error code 256

### ISSUE THREAD

**Issue by Jessica-2345** [HRGV/phyloFlash#120] opened 2020-06-25 23:28 UTC
Hi, 
After installing phyloflash, I've been trying to create the database, but the error code 256 seems to be happening. See the output of the command below.
Can you please help me to resolve the issue?
Best Regards,
Jessica

(envphyloflash)[~]$phyloFlash_makedb.pl --remote

[01:15:52] Checking for required tools.
[01:15:52] Using grep found at "/bin/grep".
[01:15:52] Using bbmap found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbmap.sh".
[01:15:52] Using bbmask found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbmask.sh".
[01:15:52] Using bowtiebuild found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bowtie-build".
[01:15:52] Using bbduk found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbduk.sh".
[01:15:52] Using barrnapHGV found at
           "/gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV".
[01:15:52] Using vsearch found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/vsearch".
[01:15:52] All required tools found.

This is phyloFlash_makedb.pl from phyloFlash.pl v3.3b3

[01:15:52] downloading latest univec from ncbi
[01:15:52]   Connecting to ftp.ncbi.nlm.nih.gov
[01:15:53]   Finding /pub/UniVec/UniVec
[01:15:54]   Found UniVec (1701925 bytes)
[01:15:54]   Found existing UniVec
[01:15:54] Sizes match. Skipping download
[01:15:54] downloading latest SSU RefNR from www.arb-silva.de
[01:15:54]   Connecting to ftp.arb-silva.de
[01:15:54]   Finding
           /current/Exports/*_SSURef_N?99_tax_silva_trunc.fasta.gz
[01:15:55]   Found SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz
           (196218395 bytes)
[01:15:55]   Found existing SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz
[01:15:55]   Verifying MD5...
[01:15:55]   Verified. Skipping download
[01:15:55] unpacking SILVA database
[01:16:19] searching for LSU contamination in SSU RefNR
[01:16:19] running subcommand:
           /gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
             --kingdom bac --threads 64 --evalue 1e-10 --gene lsu --reject
           0.01 ./138/SILVA_SSU.fasta  >tmp.barrnap_hits.bac.gff
           2>tmp.barrnap_hits.bac.barrnap.out
[01:16:36] running subcommand:
           /gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
             --kingdom arch --threads 64 --evalue 1e-10 --gene lsu --reject
           0.01 ./138/SILVA_SSU.fasta  >tmp.barrnap_hits.arch.gff
           2>tmp.barrnap_hits.arch.barrnap.out
[01:16:54] running subcommand:
           /gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
             --kingdom euk --threads 64 --evalue 1e-10 --gene lsu --reject
           0.01 ./138/SILVA_SSU.fasta  >tmp.barrnap_hits.euk.gff
           2>tmp.barrnap_hits.euk.barrnap.out
[01:17:18] Removing sequences with potential LSU contamination
[01:17:18] Number of sequences to skip: 120
[01:17:29] masking low entropy regions in SSU RefNR
[01:17:29] running subcommand:
           /home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbmask.sh
           overwrite=t -Xmx10g threads=64 in=./138//SILVA_SSU.noLSU.fasta
           out=./138//SILVA_SSU.noLSU.masked.fasta minkr=4 maxkr=8 mr=t
           minlen=20 minke=4 maxke=8 fastawrap=0
           2>tmp.bbmask_mask_repeats.log
[01:17:58] removing UniVec contamination in SSU RefNR
[01:17:58] File ./138//SILVA_SSU.noLSU.masked.trimmed.fasta exists, not
           overwriting
[01:17:58] Vsearch v2.5.0+ found, will index database to UDB file
[01:17:58] Indexing ./138//SILVA_SSU.noLSU.masked.trimmed.fasta to make UDB
           file ./138//SILVA_SSU.noLSU.masked.trimmed.udb with Vsearch
[01:17:58] WARNING: File ./138//SILVA_SSU.noLSU.masked.trimmed.udb already
           exists. Not overwriting
[01:17:58] clustering database
[01:17:58] WARNING: File ./138/SILVA_SSU.noLSU.masked.trimmed.NR99.fasta
           already exists, not overwriting
[01:17:58] WARNING: File
           ./138/SILVA_SSU.noLSU.masked.trimmed.NR99.fixed.fasta already
           exists, not overwriting
[01:17:58] creating bbmap reference
[01:17:58] WARNING: Folder ./138/ exists, not overwriting
[01:17:58] clustering database
[01:17:58] WARNING: File ./138/SILVA_SSU.noLSU.masked.trimmed.NR96.fasta
           already exists, not overwriting
[01:17:58] creating bowtie index (for emirge)
[01:17:58] running subcommand:
           /home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bowtie-build
           ./138/SILVA_SSU.noLSU.masked.trimmed.NR96.fixed.fasta
           ./138/SILVA_SSU.noLSU.masked.trimmed.NR96.fixed.bt -q
           2>tmp.bowtiebuild.log
[01:17:59] FATAL: Tool execution failed!.
           Error was '' and return code '256'
           Aborting.
[01:17:59] Saving log to file phyloFlash_log_on_error

I've install phyloFlash using Bionconda:
conda create --strict-channel-priority -c conda-forge -c bioconda -c defaults -n envphyloflash phyloflash

**Comment by kbseah** [comment] 2020-06-26 06:13
Hello @Jessica-2345 , it looks like the bowtie build step is failing, could you post the contents of the log file `tmp.bowtiebuild.log`? 
Also, it looks like you're rerunning the build script, because some of the database files are already there and have been skipped. It could be that one or more of the already built files were incomplete or corrupted if the database build failed the first time. You could try to delete the last-built file in the database prep pipeline, and if that doesn't work, delete the `138/` folder and start fresh. Given that you've already downloaded the SILVA SSU file and the UniVec file, you don't have to download them again but can supply the local path to those files with the `--silva_file` and `--univec_file` options respectively.

**Comment by Jessica-2345** [comment] 2020-06-26 07:23
[
[tmp.bowtiebuild.log](https://github.com/HRGV/phyloFlash/files/4835576/tmp.bowtiebuild.log)
]
Here is the file tmp.bowtiebuild.log.

**Comment by kbseah** [comment] 2020-06-26 07:30
bowtie-build says that the file `./138/SILVA_SSU.noLSU.masked.trimmed.NR96.fixed.fasta` is empty, looks like you should delete the contents of folder `138/` and restart the database build, because something went wrong the first time.

**Comment by Jessica-2345** [comment] 2020-06-26 10:16
Hello again,
Thanks for your help! 
After removing 138 directory and restart the database build, I had a problem during the clustering, so I looked at this previous issue that was similar https://github.com/HRGV/phyloFlash/issues/113 and changed the permissions, but the problem with the error 9 is still happening.
Below the output of the command 

(envphyloflash) [~/Phyloflash]$ phyloFlash_makedb.pl --silva_file SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz --univec_file UniVec --CPUs 16 --keep --log phyloFlash_makedb.log
[10:36:08] Checking for required tools.
[10:36:08] Using grep found at "/bin/grep".
[10:36:08] Using bowtiebuild found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bowtie-build".
[10:36:08] Using bbduk found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbduk.sh".
[10:36:08] Using bbmask found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbmask.sh".
[10:36:08] Using vsearch found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/vsearch".
[10:36:08] Using barrnapHGV found at
           "/gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV".
[10:36:08] Using bbmap found at
           "/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbmap.sh".
[10:36:08] All required tools found.

This is phyloFlash_makedb.pl from phyloFlash.pl v3.3b3

[10:36:08] using local copy of univec: UniVec
[10:36:08] using local copy of Silva SSU RefNR:
           SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz
[10:36:08] unpacking SILVA database
[10:36:31] searching for LSU contamination in SSU RefNR
[10:36:31] running subcommand:
           /gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
             --kingdom bac --threads 16 --evalue 1e-10 --gene lsu --reject
           0.01 ./138/SILVA_SSU.fasta  >tmp.barrnap_hits.bac.gff
           2>tmp.barrnap_hits.bac.barrnap.out
[10:37:02] running subcommand:
           /gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
             --kingdom arch --threads 16 --evalue 1e-10 --gene lsu --reject
           0.01 ./138/SILVA_SSU.fasta  >tmp.barrnap_hits.arch.gff
           2>tmp.barrnap_hits.arch.barrnap.out
[10:37:34] running subcommand:
           /gpfsuser/home/users/j/o/jody/miniconda3/envs/envphyloflash/lib/phyloFlash/barrnap-HGV/bin/barrnap_HGV
             --kingdom euk --threads 16 --evalue 1e-10 --gene lsu --reject
           0.01 ./138/SILVA_SSU.fasta  >tmp.barrnap_hits.euk.gff
           2>tmp.barrnap_hits.euk.barrnap.out
[10:38:18] Removing sequences with potential LSU contamination
[10:38:18] Number of sequences to skip: 120
[10:38:29] masking low entropy regions in SSU RefNR
[10:38:29] running subcommand:
           /home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/bbmask.sh
           overwrite=t -Xmx10g threads=16 in=./138//SILVA_SSU.noLSU.fasta
           out=./138//SILVA_SSU.noLSU.masked.fasta minkr=4 maxkr=8 mr=t
           minlen=20 minke=4 maxke=8 fastawrap=0
           2>tmp.bbmask_mask_repeats.log
[10:39:15] removing UniVec contamination in SSU RefNR
[10:39:15] File ./138//SILVA_SSU.noLSU.masked.trimmed.fasta exists, not
           overwriting
[10:39:15] Vsearch v2.5.0+ found, will index database to UDB file
[10:39:15] Indexing ./138//SILVA_SSU.noLSU.masked.trimmed.fasta to make UDB
           file ./138//SILVA_SSU.noLSU.masked.trimmed.udb with Vsearch
[10:39:15] WARNING: File ./138//SILVA_SSU.noLSU.masked.trimmed.udb already
           exists. Not overwriting
[10:39:15] clustering database
[10:39:15] running subcommand:
           /home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/vsearch
           --cluster_fast ./138/SILVA_SSU.noLSU.masked.trimmed.fasta --id
           0.99 --centroids ./138/SILVA_SSU.noLSU.masked.trimmed.NR99.fasta
           --notrunclabels --threads 16
vsearch v2.15.0_linux_x86_64, 252.4GB RAM, 64 cores
https://github.com/torognes/vsearch

Reading file ./138/SILVA_SSU.noLSU.masked.trimmed.fasta 100%
743916384 nt in 510691 seqs, min 800, max 3706, avg 1457
Masking 100%
Sorting by length 100%
Counting k-mers 100%
Clustering 83%[11:44:43] FATAL: Tool execution failed!.
           Error was 'No such file or directory' and return code '9'
           Aborting.

**Comment by kbseah** [comment] 2020-06-26 10:32
This is strange, because it looks like the clustering step is failing halfway through.

Could you delete the file `SILVA_SSU.noLSU.masked.trimmed.NR99.fasta` and run the makedb script again? With the default `-nooverwrite` option the existing files should not be overwritten.

If the problem persists, you could try to run the clustering command with vsearch directly, without using the makedb script: 

`/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/vsearch --cluster_fast ./138/SILVA_SSU.noLSU.masked.trimmed.fasta --id 0.99 --centroids ./138/SILVA_SSU.noLSU.masked.trimmed.NR99.fasta --notrunclabels --threads 16`

**Comment by Jessica-2345** [comment] 2020-06-26 15:23
I've tried the two possibilities and with --nooverwrite I had the same output

Reading file ./138/SILVA_SSU.noLSU.masked.trimmed.fasta 100%
743916384 nt in 510691 seqs, min 800, max 3706, avg 1457
Masking 100%
Sorting by length 100%
Counting k-mers 100%
Clustering 89%[13:59:32] FATAL: Tool execution failed!.
           Error was 'No such file or directory' and return code '9'
           Aborting.
[13:59:32] Saving log to file phyloFlash_log_on_error

And by using directly vsearch it was mentionned Killed 

(envphyloflash) [jody@node001 Phyloflash]$  /home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/vsearch --cluster_fast ./138/SILVA_SSU.noLSU.masked.trimmed.fasta --id 0.99 --centroids ./138/SILVA_SSU.noLSU.masked.trimmed.NR99.fasta --notrunclabels --threads 16
vsearch v2.15.0_linux_x86_64, 252.4GB RAM, 64 cores
https://github.com/torognes/vsearch

Reading file ./138/SILVA_SSU.noLSU.masked.trimmed.fasta 100%
743916384 nt in 510691 seqs, min 800, max 3706, avg 1457
Masking 100%
Sorting by length 100%
Counting k-mers 100%
Clustering 84%Killed

Do you know what could go wrong ?
Thanks for your help

**Comment by Jessica-2345** [comment] 2020-06-28 12:17
Hello @kbseah, I thought the problem was resolved by using 

/home/ulb/ebe/jody/miniconda3/envs/envphyloflash/bin/vsearch --cluster_fast ./138/SILVA_SSU.noLSU.masked.trimmed.fasta --id 0.99 --centroids ./138/SILVA_SSU.noLSU.masked.trimmed.NR99.fasta --notrunclabels --threads 8

But after the run was apparently done, I've tried to run 

phyloFlash.pl -dbhome /home/ulb/ebe/jody/Phyloflash/138

and the result output was : 

This is phyloFlash v3.3b3

Broken dbhome directory: missing file "/home/ulb/ebe/jody/Phyloflash/138/ref/genome/1/summary.txt"
Usage:
    phyloFlash.pl [OPTIONS] -lib name -read1 <file> -read2 <file>

    phyloFlash.pl -help

    phyloFlash.pl -man

    phyloFlash.pl -check_env

I check the 138/ directory but there was no ref/ directory.

Here's the output of the tmp.vsearch_make_udb.log

WARNING: The makeudb_usearch command does not support multithreading.
Only 1 thread used.
vsearch v2.15.0_linux_x86_64, 252.4GB RAM, 64 cores
https://github.com/torognes/vsearch

Reading file ./138//SILVA_SSU.noLSU.masked.trimmed.fasta 100%
743916384 nt in 510691 seqs, min 800, max 3706, avg 1457
Masking 100%
Counting k-mers 100%
Creating k-mer index 100%
Writing UDB file 100%

Thanks for your help!
Jessica

**Comment by kbseah** [comment] 2020-06-29 08:20
Hello @Jessica-2345 , 

From what I can tell, Vsearch failed with 16 CPUs but worked with 8, is that correct? I suspect that with 16 CPUs there is some resource used that is exceeding the user quota on your system and causing the job to be killed. Unfortunately in that scenario the problem would not be easily reproducible as it would potentially affect each system in a different way, but it would still be good to know what happens so we can suggest fixes to other users who encounter this issue.

In your latest reply, you also stated that the database didn't work after running Vsearch separately. That's because Vsearch is used to cluster the reference sequences, which are then indexed and further processed by other programs.

Could you use phyloFlash_makedb.pl with the `--nooverwrite` option as before, to continue the database processing and pick it up where it was left off by Vsearch?

Best regards,
Brandon

**Comment by Jessica-2345** [comment] 2020-06-29 20:32
Everything worked fine, thank you for your help! 

Best regards,
Jessica

**Comment by kbseah** [comment] 2020-06-30 09:40
You're welcome!

**Comment by kbseah** [comment] 2020-10-04 16:01
@HRGV i think we can close this issue as it appears to have been resolved

**Closed** 2020-10-04 18:10 UTC
